ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# NGC images contain user owned files in /usr/lib
RUN chown root:root /usr/lib

# Copy various shell scripts that group dependencies for install
#COPY dockerfile_scripts /tmp/det_dockerfile_scripts
# Copy shell scripts as needed so that a simple change to one of those
# scripts does not cause this image and all derived images from being
# completely rebuilt. This can save significant build time, especially for
# the HPC images.
ARG SCRIPT_DIR=/tmp/det_dockerfile_scripts
RUN mkdir -p ${SCRIPT_DIR}

COPY dockerfile_scripts/install_deb_packages.sh ${SCRIPT_DIR}
COPY dockerfile_scripts/add_det_nobody_user.sh ${SCRIPT_DIR}
COPY dockerfile_scripts/install_libnss_determined.sh ${SCRIPT_DIR}
COPY dockerfile_scripts/libnss_determined ${SCRIPT_DIR}/libnss_determined
RUN ${SCRIPT_DIR}/install_deb_packages.sh
RUN ${SCRIPT_DIR}/add_det_nobody_user.sh
RUN ${SCRIPT_DIR}/install_libnss_determined.sh

# We uninstall these packages after installing. This ensures that we can
# successfully install these packages into containers running as non-root.
# `pip` does not uninstall dependencies, so we still have all the dependencies
# installed.
RUN python -m pip install determined && python -m pip uninstall -y determined

COPY dockerfile_scripts/additional-requirements-torch.txt ${SCRIPT_DIR}
COPY dockerfile_scripts/additional-requirements.txt ${SCRIPT_DIR}
RUN python -m pip install  \
    -r ${SCRIPT_DIR}/additional-requirements-torch.txt \
    -r ${SCRIPT_DIR}/additional-requirements.txt

COPY dockerfile_scripts/notebook-requirements.txt ${SCRIPT_DIR}
RUN python -m pip install -r ${SCRIPT_DIR}/notebook-requirements.txt && \
    jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

ENV JUPYTER_CONFIG_DIR=/run/determined/jupyter/config
ENV JUPYTER_DATA_DIR=/run/determined/jupyter/data
ENV JUPYTER_RUNTIME_DIR=/run/determined/jupyter/runtime

COPY dockerfile_scripts/install_google_cloud_sdk.sh ${SCRIPT_DIR}
RUN ${SCRIPT_DIR}/install_google_cloud_sdk.sh

ENV DEEPSPEED_PIP="deepspeed==0.13.0"
COPY dockerfile_scripts/install_deepspeed.sh ${SCRIPT_DIR}
RUN ${SCRIPT_DIR}/install_deepspeed.sh

RUN rm -r /tmp/*
