#!/bin/bash

UCX_INSTALL_DIR=/container/ucx
OMPI_INSTALL_DIR=/container/ompi
MPICH_INSTALL_DIR=/container/mpich
OFI_INSTALL_DIR=/container/ofi
ROCM_DIR=/opt/rocm
export ROCM_DIR

# Make sure OMPI/UCX show up in the right paths
VERBS_LIB_DIR=/usr/lib/libibverbs
UCX_LIB_DIR=${UCX_INSTALL_DIR}/lib:${UCX_INSTALL_DIR}/lib64
UCX_PATH_DIR=${UCX_INSTALL_DIR}/bin
OFI_LIB_DIR=${OFI_INSTALL_DIR}/lib:${OFI_INSTALL_DIR}/lib64
OFI_PATH_DIR=${OFI_INSTALL_DIR}/bin
OMPI_LIB_DIR=${OMPI_INSTALL_DIR}/lib
OMPI_PATH_DIR=${OMPI_INSTALL_DIR}/bin
MPICH_LIB_DIR=${MPICH_INSTALL_DIR}/lib
MPICH_PATH_DIR=${MPICH_INSTALL_DIR}/bin
export UCX_LIB_DIR
export UCX_PATH_DIR
export OFI_LIB_DIR
export OFI_PATH_DIR
export OMPI_LIB_DIR
export OMPI_PATH_DIR
export MPICH_LIB_DIR
export MPICH_PATH_DIR

# Set up UCX_LIBS and OFI_LIBS
UCX_LIBS="${VERBS_LIB_DIR}:${UCX_LIB_DIR}:${OMPI_LIB_DIR}:"
OFI_LIBS="${VERBS_LIB_DIR}:${OFI_LIB_DIR}:${MPICH_LIB_DIR}:"

# If WITH_OFI is true, then set EXTRA_LIBS to OFI libs, else set to empty string
EXTRA_LIBS="${WITH_OFI:+${OFI_LIBS}}"

# If EXTRA_LIBS is empty, set to UCX libs, else leave as OFI libs
EXTRA_LIBS="${EXTRA_LIBS:-${UCX_LIBS}}"
export EXTRA_LIBS

# But, only add them if WITH_MPI
LD_LIBRARY_PATH=${WITH_MPI:+$EXTRA_LIBS}$LD_LIBRARY_PATH

#USING OFI
PATH=${WITH_OFI:+$PATH:${WITH_MPI:+$OFI_PATH_DIR:$MPICH_PATH_DIR}}

#USING UCX
PATH=${PATH:-$CONDA:${WITH_MPI:+$UCX_PATH_DIR:$OMPI_PATH_DIR}}

PATH=$OMPI_PATH_DIR:$OFI_INSTALL_DIR:$PATH
export PATH

# Enable running OMPI as root
export OMPI_ALLOW_RUN_AS_ROOT ${WITH_MPI:+1}
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM ${WITH_MPI:+1}

AWS_PLUGIN_INSTALL_DIR=/container/aws
export AWS_PLUGIN_INSTALL_DIR

LD_LIBRARY_PATH=${WITH_OFI:+$AWS_PLUGIN_INSTALL_DIR:}$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
