---
- name: apt-get update, apt-get upgrade.
  become: yes
  apt:
    update_cache: yes
    upgrade

- name: Install utility packages.
  become: yes
  apt:
    name:
    - curl
    - git
    - htop
    - iftop
    - iotop
    - lsof
    - net-tools
    - screen
    - tmux
    - tree
    - unzip
    - wget
    - zip
    - nfs-common
    state: present
