---
- name: Install utility packages.
  become: yes
  apt:
    name:
    - python3-pip

- name: Install Docker Python SDK
  become: yes
  pip:
    name:
      - docker
    state: present

- name: Start and enable Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull tf1 GPU environment
  become: yes
  docker_image:
    name: "{{ gpu_tf1_environment_name }}{{ image_suffix }}"
    source: pull

- name: Pull tf1 CPU environment
  become: yes
  docker_image:
    name: "{{ cpu_tf1_environment_name }}{{ image_suffix }}"
    source: pull

- name: Pull TF2 CPU environment
  become: yes
  docker_image:
    name: "{{ cpu_tf2_environment_name }}{{ image_suffix }}"
    source: pull

- name: Pull CUDA 11 environment
  become: yes
  docker_image:
    name: "{{ cuda_11_environment_name }}{{ image_suffix }}"
    source: pull
