---
- name: Install utility packages.
  become: yes
  apt:
    name:
    - python3-pip

- name: Install Docker Python SDK
  become: yes
  pip:
    name:
      - docker
    state: present

- name: Start and enable Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull TF2 CPU environment
  become: yes
  shell: |
    docker pull "{{ cpu_tf2_environment_name }}{{ image_suffix }}"
  args:
    executable: /bin/bash

- name: Pull TF2 GPU environment
  become: yes
  shell: |
    docker pull "{{ gpu_tf2_environment_name }}{{ image_suffix }}"
  args:
    executable: /bin/bash
